cygwin libxft support if possible update utf8 documentation

diff --git a/.github/workflows/binaries-cygwin.yml b/.github/workflows/binaries-cygwin.yml
--- a/.github/workflows/binaries-cygwin.yml
+++ b/.github/workflows/binaries-cygwin.yml
@@ -25,6 +25,8 @@ jobs:
           libncurses-devel 
           libXt-devel
           libXft-devel
+          pkg-config
+          freetype
           fontconfig 
           zip 
           unzip
@@ -82,7 +84,9 @@ jobs:
         cd microemacs
         export VRS=`grep -E '^#define me(YEAR|MONTH|DAY)' src/evers.h | awk '{ print $3 }' | paste -sd '' | sed 's/"//g'`
         echo "VRS=$VRS" >> $GITHUB_ENV
-        echo "VRS=$VRS"        
+        echo "VRS=$VRS"
+        make -f cygwin.gmk default
+        pkg-config --exists xft && echo "XFT: found" || echo "XFT: missing"
         make -f cygwin.gmk bfs/bin
         make -f cygwin.gmk mec  
         make -f cygwin.gmk mecb
